metrics_port = 6942
metrics_host = "idkwhatthisistbh"

[database_config]
listener_channel="backfill_item_added"
url = "postgresql://postgres:postgres@localhost:5432/nfts?ssl_mode=false"

[messenger_config]
messenger_type = "Redis"
connection_config = { "redis_connection_str" = "redis://localhost/"}

[rpc_config]
url = "http://localhost:8899"
commitment = "finalized"