apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ingest.secret" . }}
data:
  DATABASE_URL: {{ .Values.ingest.db_url | b64enc | quote }}
  INGESTER_DATABASE_CONFIG: {{ ( printf "{listener_channel=\"backfill_item_added\", url=\"%s\"}" .Values.ingest.db_url ) | b64enc | quote }}
  INGESTER_MESSENGER_CONFIG: {{ ( printf "{connection_config={batch_size=%d,idle_timeout=%d,message_wait_timeout=%d,redis_connection_str=%s}, messenger_type=\"Redis\"}" (.Values.ingest.batch_size | int64 | quote ) ( .Values.ingest.idle_timeout | int64 | quote ) ( .Values.ingest.message_wait_timeout | int64 | quote ) .Values.ingest.redis_url ) | b64enc | quote }}
  INGESTER_RPC_CONFIG: {{ ( printf "{url=%s, commitment=\"finalized\"}" .Values.ingest.rpc_url ) | b64enc | quote }}
