name: Build & Test
on:
  push:
  pull_request:
    branches:
      - main
env:
  RUST_TOOLCHAIN: stable
jobs:
  build-api:
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cd das_api
          cargo build
        shell: bash
  build-ingest:
    runs-on: buildjet-8vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cd nft_ingester
          cargo build
        shell: bash




